### ISSUE TITLE
Error when training model using multiple types of images

### ISSUE THREAD

**Issue by ycseong07** [statgarten/playdoh#13]
**Problem**

While training a model utilizing both PNG and JPG formats, the following error arose:
```
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
```
**Solution**

The code below resolves the issue by opening the image file as a temporary file, converting it to an RGB format, and saving it as a JPEG file.

```python
image_tmp = Image.open(BytesIO(file_byte))
image_rgb = image_tmp.convert('RGB')
byte_arr = BytesIO()
image_rgb.save(byte_arr, format='JPEG')
file_byte_rgb = byte_arr.getvalue()
file_bytes_list.append(('files', BytesIO(file_byte_rgb)))
```

**Comment by MinDongRyul** [comment]
png, jpg같은 확장자가 다른 파일에 있어서 공통적인 채널 수를 조정 함으로 에러 해결(#15)
