### ISSUE TITLE
0525 피드백

### ISSUE THREAD

**Issue by ycseong07** [statgarten/playdoh#16]
1. 한글 - 영어 토글 버튼 개발 필요
    - https://stackoverflow.com/questions/74336582/button-to-switch-languages-in-streamlit

2. Streamlit에서 제공하는 기본 위젯에 표시되는 영어 명령어 바꿀 수 있는지 확인 필요

3. Train 시 진행률 bar 표시가능한지 확인 필요
    - server.py에서의 진행 정도를 받아 UI에 표시 가능할지?

4. Class 수 선택하는 옵션을 Sidebar가 아닌 Main page에 표기

**Comment by MinDongRyul** [comment]
한글 - 영어 토글 버튼 개발 필요
- https://stackoverflow.com/questions/74336582/button-to-switch-languages-in-streamlit
-> 5월 25일 16시 기준 if else문을 통하여 한글-영어 버튼 개발
-> 5월 26일 9시 기준 if else문을 통해서 구현 하되 중복된 코드는 하나의 함수로 만들어 처리
-> 5월 26일 16시 기준 한글/영어 각각의 json파일을 locale폴더에 구성 후 버튼 클릭시 해당 json파일을 불러서 번역하는 식의 방향으로 구성

Streamlit에서 제공하는 기본 위젯에 표시되는 영어 명령어 바꿀 수 있는지 확인 필요
-> css수정을 통하여 기본 위젯에 표시되는 영어 명령어 텍스트 변경

Train 시 진행률 bar 표시가능한지 확인 필요
- server.py에서의 진행 정도를 받아 UI에 표시 가능할지?
-> 진행률 bar에 대해 progress bar를 사용할 지, epoch를 표출할 지에 대해 탐색중

Class 수 선택하는 옵션을 Sidebar가 아닌 Main page에 표기
-> 코드 수정을 통해 Main page에 class_add_button, class_del_button 추가
