### ISSUE TITLE
시계열 분석 예시파일 제공

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/playdoh#41]
<img width="1081" alt="스크린샷 2023-08-23 오후 4 43 16" src="https://github.com/statgarten/playdoh/assets/28377612/079883d8-a628-448f-9ee9-66cefac64b1c">

시계열 분석 시 파일업로드할 포맷이 담긴 예시파일을 같이 제공하면 좋겠습니다!

**Comment by ycseong07** [comment]
@MinDongRyul  sample button 추가해주시고, 누르면 샘플 파일 업로드되도록 수정해주세요

**Comment by MinDongRyul** [comment]
@ycseong07 네 알겠습니다.

**Comment by ycseong07** [comment]
#42
