### ISSUE TITLE
When using wav2vec model, the session is killed

### ISSUE THREAD

**Issue by ycseong07** [statgarten/playdoh#6]

**Comment by ycseong07** [comment]
1. local server에서 model load - prediction 과정 처리한 후, FastAPI로 해당 결과만 받아와서 dashboard에 출력하는 방법

**Comment by chandryou** [comment]
local server는 중앙에서 누군가가 운영하고 있어야 하는거죠..? 
NAVER CLOVA 등의 cloud API에 붙이면 안 될까요? 로그인 필요로 하고요..

**Comment by ycseong07** [comment]
회의 때 나왔던 내용처럼 NAVER CLOVA API를 붙여볼 수도 있습니다. 다만 패키지를 로컬(오프라인)/웹/Docker/AMI의 4가지 형태로 배포해야 하고, API를 붙일 경우 로컬(오프라인) 버전에서는 작동하지 않을 거라서 wav2vec 모델을 다운 받아 사용하는 방법을 사용해보고 있습니다. 혹시 제가 착각하고 있는지 싶은데, 로컬 버전이 오프라인 환경을 의미하지는 않는 걸까요?

local server는 로컬/웹/Docker 버전에서는 사용자의 컴퓨터, AMI 버전에서는 EC2로 정의할 수 있을 것 같습니다.

**Comment by ycseong07** [comment]
686b5a51b890dc4ebbf9694f04b52d161f4b5d35
